# Generated by Django 3.1.3 on 2020-11-17 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='coffee_store',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=150)),
                ('city', models.TextField()),
                ('state', models.CharField(max_length=2)),
                ('email', models.EmailField(max_length=254)),
            ],
            options={
                'db_table': 'coffee_store',
            },
        ),
    ]
