# Generated by Django 3.1.3 on 2020-11-17 16:09

from django.db import migrations


def load_stores(apps, schema_editor):
    Store = apps.get_model("coffee_store", "coffee_store")
    store_corporate = Store(id=0, name='Corporate', address='624 Broadway', city='San Diego',
                            state='CA', email='corporate@coffeehouse.com')
    store_corporate.save()
    store_downtown = Store(id=1, name='Downtown', address='Horton Plaza', city='San Diego',
                           state='CA', email='downtown@coffeehouse.com')
    store_downtown.save()
    store_uptown = Store(id=2, name='Uptown', address='1240 University Ave',
                         city='San Diego', state='CA', email='uptown@coffeehouse.com')
    store_uptown.save()
    store_midtown = Store(id=3, name='Midtown', address='784 W Washington St',
                          city='SanDiego', state='CA', email='midtown@coffeehouse.com')
    store_midtown.save()


def delete_stores(apps, schema_editor):
    Store = apps.get_model("coffee_store", "coffee_store")
    Store.objects.all().delete()


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ('coffee_store', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(load_stores),
    ]
