# Generated by Django 3.1.3 on 2020-11-19 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coffee_store', '0004_remove_coffee_store_amenities'),
    ]

    operations = [
        migrations.AddField(
            model_name='coffee_store',
            name='amenities',
            field=models.ManyToManyField(blank=True, to='coffee_store.Amenity'),
        ),
    ]
